### ISSUE TITLE
Feature: Compatibility with OLLAMA, locally hosted AI LLMS

### ISSUE THREAD

**Issue by pghpete** [danielmiessler/fabric#101]
First, thank you for the tremendous project! I love it.

I am currently a proponent of OLLAMA and locally hosted LLMs. It would be awesome if, as a long-term goal, we could integrate fabric in to a locally hosted LLM. 

Ollama does use openai apis etc. but I believe the goal would be to use the locally hosted LLMs over openai if that is what you wished.

[https://github.com/ollama/ollama](https://github.com/ollama/ollama)

I would love to offer up my help in testing with my ollama installation if I can.

**Comment by danielmiessler** [comment]
Yes, we're looking to do what Chris put there to integrate LIteLLM to be able to pivot to different LLMs.

**Comment by danielmiessler** [comment]
Yes, we're looking to do what Chris put there to integrate LIteLLM to be able to pivot to different LLMs.

**Comment by bknasmueller** [comment]
@danielmiessler and @pghpete I set this up for myself before seeing this issue and documented the setup here, just FYI in case it helps your implementation: https://knasmueller.net/running-fabric-locally-with-ollama

Works great for me with Mistral

**Comment by mozg31337** [comment]
> @danielmiessler and @pghpete I set this up for myself before seeing this issue and documented the setup here, just FYI in case it helps your implementation: https://knasmueller.net/running-fabric-locally-with-ollama
> 
> Works great for me with Mistral

I tried to follow your guide, but it doesn't work for me. Get 404:
[GIN] 2024/02/21 - 23:33:37 | 404 |       4.042µs |       127.0.0.1 | POST     "/v1/chat/completions"

typical successful api request response looks like this:
[GIN] 2024/02/21 - 23:23:44 | 200 |  2.509987209s |       127.0.0.1 | POST     "/api/generate"

**Comment by waldo323** [comment]
mozg31337, have you already checked to make sure ollama is running on the port specified?  

If it is, try restarting the service. 
If it is not running try starting it and then make sure it is running on the expected port.
If you're still having trouble, make sure you're running the latest ollama.

I was able to get it running with their instructions earlier today. 
While I also ran into a 404 error at first, I didn't dig into *why* it wasn't responding. I did stop the process and start it fresh.  ( It likely wouldn't have been a helpful dive into why, as I installed the latest ollama today over the previous installation. when I looked at the process list before stopping ollama, the ollama process showed it had been running since the 13th)
