### ISSUE TITLE
[Bug]: transcript not available. (transcript not found)

### ISSUE THREAD

**Issue by buylife** [danielmiessler/fabric#1037]
### What happened?

I was doing this:
`fabric --youtube "https://www.youtube.com/watch?v=a1XKmXL2dUQ" --stream --pattern extract_wisdom`

when THAT output happened:
`transcript not available. (transcript not found)`

I was expecting that I'd get the video processed through the pattern.

My thouths on this: 
1. I can see that the video has both English and English auto-generated subtitles. So the behavior of the program makes no sense to me. 
2. By the way, I get the same output when I try to use a video without pre-uploaded subtitles (just auto-generated), so this case completely makes no sense and makes Fabric nearly useless. I would say that not all videos on YouTube have subtitles, so... What's wrong with me? What I'm doing wrong? 

Thank you for your time.

### Version check

- [X] Yes I was.

**Comment by jambronner** [comment]
I'm having the same issue. Any yt video i try i get the "transcript not available. (transcript not found)" error

**Comment by buylife** [comment]
What’s up with the YouTube API? Any changes?

**Comment by eugeis** [comment]
I can't reproduce:

❯ fabric --youtube "https://www.youtube.com/watch?v=a1XKmXL2dUQ"
The evolution of the smartphone industry, particularly with the introduction of the iPhone, has been nothing short of revolutionary. When Apple released the first iPhone in 2007, it marked a significant departure from the norm with its giant screen and lack of physical buttons. Despite initial skepticism due to missing features like Bluetooth and 3G cellular data, the iPhone quickly captured consumer interest and redefined the mobile phone landscape. Dominant brands like Nokia and Blackberry struggled to adapt, while tech giants like Samsung and Apple leveraged their expertise to innovate and dominate the market.

In the early years, the pace of innovation was rapid, with each new iPhone model introducing significant changes. The iPhone 3G brought better internet connectivity and the App Store, which revolutionized mobile applications. The iPhone 4 introduced the Retina display and front-facing camera, while the 4S brought 1080p video recording and Siri. Subsequent models continued to introduce notable features such as Touch ID, Apple Pay, and enhanced camera capabilities.

However, over time, the pace of innovation has slowed. The form factor changes have become less frequent, and many of the new features are incremental improvements rather than groundbreaking innovations. For instance, the much-criticized notch introduced with the iPhone X has persisted in various forms for several generations, indicating a technological compromise. Consumers are now holding onto their phones for longer periods, with the average upgrade cycle increasing.

This slowdown in innovation has prompted manufacturers to explore new product categories and features to maintain consumer interest. Wearables like smartwatches and foldable phones have emerged, although they often face durability challenges and mixed reviews. Despite these efforts, the market has become saturated, and the pressure to release a new, exciting phone every year has led to ethical and environmental concerns.

The environmental impact of frequent phone upgrades is significant. Manufacturing new devices generates emissions and pollution, and while recycling is better than landfill, it still creates environmental harm. Additionally, issues such as the use of child labor in cobalt mining for batteries highlight the ethical challenges in the tech supply chain.

As tech companies continue to navigate these challenges, regulatory bodies like the EU are pushing for more stringent regulations to address monopolistic behavior and other issues. The evolving landscape of AI and its implications further complicate the picture, suggesting that the era of unchecked growth and innovation in the tech industry may be coming to an end.

For more insights and updates on the latest tech trends and innovations, be sure to subscribe to our channel and stay tuned for our next video. Thanks for watching!

**Comment by eugeis** [comment]
❯ fabric --youtube "https://www.youtube.com/watch?v=a1XKmXL2dUQ" --stream --pattern extract_wisdom
# SUMMARY
A discussion on the evolution of smartphones, focusing on Apple's iPhone, its innovations, market impact, and ethical considerations in tech manufacturing.

# IDEAS:
- "Apple released the first iPhone in 2007, sparking a revolution in the phone industry."
- "Initial lukewarm reviews of the iPhone were due to its lack of physical buttons and missing features."
- "Nokia and BlackBerry were ousted by broader tech manufacturers like Samsung and Apple."
- "Technical innovation and one-upmanship made it hard for incumbent brands to keep up."
- "Recent years show phone manufacturers falling into a more iterative release schedule."
- "The iPhone 10's notch was introduced 10 years after the original iPhone."
- "The iPhone 3G introduced better internet connectivity and the App Store."
- "The iPhone 4 introduced the Retina screen and the front-facing selfie camera."
- "The 4S brought in 1080P video recording, iMessage, iCloud, and Siri."
- "The iPhone 5 had 4G and the Lightning connector."
- "The iPhone 5S had the Touch ID fingerprint sensor."
- "The iPhone 6 featured Apple Pay, a mass-adopted feature."
- "Bendgate occurred because the iPhone 6 was made too thin and light."
- "Apple Pay made the company an estimated $1.9 billion in 2022."
- "3D Touch was a force-sensing feature on the screen for additional options."
- "The iPhone 7 introduced dual cameras but removed the headphone jack."
- "The iPhone 8 had the True Tone display, wireless charging, and portrait mode."
- "Face Unlock was introduced in the iPhone X to accommodate a larger display."
- "Recent iPhones have faster displays and improved battery life."
- "The iPhone 15's move to USB-C was due to EU legislation."
- "Consumers are keeping handsets longer, with the average upgrade cycle increasing."
- "Sales of smartphones have slowed from their peak in 2018."
- "Wearables like smartwatches and hyper-premium offshoot phones diversify slowing sales."
- "Foldable phones had initial hardware issues but are now a growing segment."
- "The iPad series exemplifies the slowdown in innovation more than anything."
- "Apple is expanding tool sets for video professionals in their devices."
- "AI implementation in devices ranges from useful language translation to gimmicky image generation."
- "Dwindling sales and forced innovation raise ethical questions around mass manufacturing."
- "Top-tier phones remain very usable at the average replacement cycle of 3.6 years."
- "Apple owns 58.81% of the market share in the USA."
- "Recycling practices still create greenhouse emissions and pollution."
- "Issues around tech manufacturing include slave labor and child labor for mining cobalt."
- "Apple has pledged to use 100% recycled cobalt by 2025."
- "Tech brands dominate the list of richest companies."
- "The EU is pushing laws to regulate monopolistic behavior of large tech brands."
- "The founder of Telegram was arrested for refusal to moderate criminal activity on his app."
- "There are calls for Elon Musk to be held accountable for Twitter's involvement in UK riots."
- "The impending concerns over AI use might end the free ride for tech companies."

# INSIGHTS:
- Initial iPhone skepticism turned into a mobile phone revolution, shifting market dominance to tech giants.
- Iterative updates now dominate the smartphone market, slowing groundbreaking innovations.
- Significant iPhone innovations include App Store, Retina screen, and biometric security.
- Consumers are holding onto smartphones longer, reflecting a shift in upgrade cycles.
- Ethical issues in tech manufacturing, like cobalt mining, challenge the industry's responsibility.
- Regulatory pressures from the EU aim to curb monopolistic behavior of large tech brands.
- The iPhone's evolution showcases the balance between consumer demand and technological limitations.
- Foldable phones illustrate the risks and rewards of pushing hardware innovation boundaries.
- AI features in smartphones range from practical to ethically questionable, impacting consumer trust.
- Mass manufacturing's environmental impact raises questions about sustainable tech practices.

# QUOTES:
- "Apple released the first iPhone in 2007, sparking a revolution in the phone industry."
- "Nokia and BlackBerry were ousted by broader tech manufacturers like Samsung and Apple."
- "Technical innovation and one-upmanship made it hard for incumbent brands to keep up."
- "Recent years show phone manufacturers falling into a more iterative release schedule."
- "The iPhone 3G introduced better internet connectivity and the App Store."
- "The iPhone 4 introduced the Retina screen and the front-facing selfie camera."
- "The iPhone 5 had 4G and the Lightning connector."
- "The iPhone 6 featured Apple Pay, a mass-adopted feature."
- "Bendgate occurred because the iPhone 6 was made too thin and light."
- "Apple Pay made the company an estimated $1.9 billion in 2022."
- "The iPhone 7 introduced dual cameras but removed the headphone jack."
- "Recent iPhones have faster displays and improved battery life."
- "The iPhone 15's move to USB-C was due to EU legislation."
- "Consumers are keeping handsets longer, with the average upgrade cycle increasing."
- "Sales of smartphones have slowed from their peak in 2018."
- "Foldable phones had initial hardware issues but are now a growing segment."
- "The iPad series exemplifies the slowdown in innovation more than anything."
- "Apple is expanding tool sets for video professionals in their devices."
- "AI implementation in devices ranges from useful language translation to gimmicky image generation."
- "Dwindling sales and forced innovation raise ethical questions around mass manufacturing."
- "Issues around tech manufacturing include slave labor and child labor for mining cobalt."
- "Apple has pledged to use 100% recycled cobalt by 2025."
- "The EU is pushing laws to regulate monopolistic behavior of large tech brands."
- "The founder of Telegram was arrested for refusal to moderate criminal activity on his app."
- "There are calls for Elon Musk to be held accountable for Twitter's involvement in UK riots."

# HABITS:
- "Consumers are keeping handsets longer, with the average upgrade cycle increasing."
- "Top-tier phones remain very usable at the average replacement cycle of 3.6 years."
- "There is a trend of opting for cheaper or older models to save money."
- "Recycling streams and large secondhand markets exist for older devices."
- "Apple has pledged to use 100% recycled cobalt by 2025."
- "Apple is expanding tool sets for video professionals in their devices."
- "Consumers frequently opt for cheaper or older models to save money."
- "Phone manufacturers falling into a more iterative release schedule."
- "Wearables like smartwatches diversify slowing sales."
- "Foldable phones are now a growing segment despite initial hardware issues."
- "Mass manufacturing's environmental impact raises questions about sustainable tech practices."
- "The iPad series exemplifies the slowdown in innovation."
- "AI implementation in devices ranges from useful to gimmicky."
- "The iPhone's evolution showcases the balance between consumer demand and technological limitations."
- "Apple Pay made the company an estimated $1.9 billion in 2022."

# FACTS:
- "Apple released the first iPhone in 2007, sparking a revolution in the phone industry."
- "Nokia and BlackBerry were ousted by broader tech manufacturers like Samsung and Apple."
- "The iPhone 3G introduced better internet connectivity and the App Store."
- "The iPhone 4 introduced the Retina screen and the front-facing selfie camera."
- "The iPhone 5 had 4G and the Lightning connector."
- "The iPhone 6 featured Apple Pay, a mass-adopted feature."
- "Apple Pay made the company an estimated $1.9 billion in 2022."
- "The iPhone 7 introduced dual cameras but removed the headphone jack."
- "Consumers are keeping handsets longer, with the average upgrade cycle increasing."
- "Sales of smartphones have slowed from their peak in 2018."
- "Wearables like smartwatches diversify slowing sales."
- "Foldable phones had initial hardware issues but are now a growing segment."
- "The iPad series exemplifies the slowdown in innovation."
- "AI implementation in devices ranges from useful language translation to gimmicky image generation."
- "Dwindling sales and forced innovation raise ethical questions around mass manufacturing."
- "Top-tier phones remain very usable at the average replacement cycle of 3.6 years."
- "Apple owns 58.81% of the market share in the USA."
- "Recycling practices still create greenhouse emissions and pollution."
- "Issues around tech manufacturing include slave labor and child labor for mining cobalt."
- "Apple has pledged to use 100% recycled cobalt by 2025."

# REFERENCES:
- "Apple"
- "Samsung"
- "Nokia"
- "BlackBerry"
- "iPhone 3G"
- "iPhone 4"
- "iPhone 5"
- "iPhone 6"
- "iPhone 7"
- "iPhone X"
- "Apple Pay"
- "USB-C"
- "iPad Pro"
- "MacBook Air"
- "Black Magic's Da Vinci video editing software"
- "Telegram"
- "Elon Musk"
- "Twitter"

# ONE-SENTENCE TAKEAWAY
Apple's iPhone revolutionized mobile phones, but recent iterative updates and ethical concerns challenge tech innovation's sustainability.

# RECOMMENDATIONS
- "Consumers should consider the environmental impact of frequent phone upgrades."
- "Phone manufacturers should prioritize sustainable and ethical practices in tech manufacturing."
- "Regulatory bodies need to curb monopolistic behavior in the tech industry."
- "Consumers should explore wearables and hyper-premium devices cautiously."
- "Tech companies must balance innovation with practical consumer needs."
- "AI features in smartphones should be developed with ethical considerations."
- "Manufacturers should focus on meaningful upgrades rather than iterative changes."
- "Expand toolsets for professional niches to create new market opportunities."
- "Tech companies should address the ethical implications of cobalt mining."
- "Increased transparency in tech manufacturing processes is necessary."
- "Consumers should utilize recycling streams and secondhand markets."
- "Innovative features should benefit consumers more than the company."
- "Regulatory pressures should be welcomed to ensure fair market practices."
- "Sustainable tech practices should become an industry standard."
- "Tech brands should invest in solving significant geopolitical and climate issues."

**Comment by buylife** [comment]
The problem was with my connection. Got that fixed.

**Comment by technotion** [comment]
I'm having this same problem. Can you elaborate on the fix?

**Comment by buylife** [comment]
> I'm having this same problem. Can you elaborate on the fix?

I ended up just picking a different VPN. Not sure if that'll work for you, though.

**Comment by technotion** [comment]
That didn't work on my end.

The error I receive is: "no matches found: ... " 

It doesn't seem to recognize any Youtube URL.

**Comment by eugeis** [comment]
"no matches found: ... " means your shell, probably tries to match characters like *,?,.... 
I need to use quotation marks around the "url", because URL may have ? inside

see my example above

**Comment by officiallymarky** [comment]
I haven't been able to use yt either, I have an API key setup.  I just get transcript not available. (EOF) everytime.  I made a simple python script that uses youtube_transcript_api module and it works fine.  So I know it isn't something on my end.

**Comment by digitalextremist** [comment]
This was due to lockdown of `YouTube` preventing most VPNs. Have since dropped `fabric` and started removing `YouTube` also. But for those curious, the root issues surrounding `YouTube` access over a VPN are/were best being addressed here:

https://github.com/iv-org/invidious/issues/4734

**Comment by officiallymarky** [comment]
> This was due to lockdown of `YouTube` preventing most VPNs. Have since dropped `fabric` and started removing `YouTube` also. But for those curious, the root issues surrounding `YouTube` access over a VPN are/were best being addressed here:
> 
> [iv-org/invidious#4734](https://github.com/iv-org/invidious/issues/4734)

I am having no trouble with or without my NordVPN connection when using Python and Youtube_transcript_api module.  It is only while using fabric I have an issue.

What did you replace fabric with?  Or do you just mean using Fabric for YouTube transcripts?

**Comment by digitalextremist** [comment]
I learned everything I could from the `fabric` approach ( which is >90% prompt writing ) and put together an arsenal/library of my own prompts directly usable in my own scripts, various LAN/WAN interfaces, and especially in [`Zed`](https://zed.dev).

Telemetry and other concerns are what nudged me out of `fabric` once I saw there is a fundamental disconnect between the `Daniel Miessler` way of seeing the landscape, and the way it is. His definition of `Human` for example, does not land.

Phenomenal prompt writer, seemingly immersed reporter on the edge of a world that does not exist but thinks it does. Once you see that prompt aspect ( kind of the same as with vertical urination early on ) you don't need to linger in that whole vibe.

There were also huge problems with the prompts themselves once I saw what was actually going on. But such is the way of all things... you start from the best set of mistakes, and then realize the underlying dynamics and break away.

**Comment by borisuu** [comment]
I've had a similar problem, for me the reason seems to have been a combination between missing `yt-dlp` and using the binary distribution, instead of the Go installation method.
After I installed `fabric` using Go, installed `yt-dlp` and setup the `~/yt-dlp.conf` with contents `--cookies-from-browser chrome`, it worked fine.
Hope this helps someone.

**Comment by ksylvan** [comment]
Everyone, please ensure that you are using the latest version of yt-dlp ( 2025.06.09) with Fabric.

**Comment by officiallymarky** [comment]
> Everyone, please ensure that you are using the latest version of yt-dlp ( 2025.06.09) with Fabric.

My problem was I didn't have yt-dlp installed, I wasn't aware it was a requirement.
After installing it, I had problems with anti-bot and it didn't work anyway.  I tested with yt-dlp alone, and no luck.  Had to have it grab cookies as well.

My python script that uses google _transcripts package worked fine and ended up using that since it just works.

**Comment by ksylvan** [comment]
@officiallymarky `yt-dlp` works if it's the latest release. They're always one step ahead of the anti-bot arms race with Google.

**Comment by officiallymarky** [comment]
> [@officiallymarky](https://github.com/officiallymarky) `yt-dlp` works if it's the latest release. They're always one step ahead of the anti-bot arms race with Google.

No luck for me.
With NordVPN, I get 403 not allowed.  Disconnected from VPN I get Did not get any data blocks.
Using python youtube-transcripts package, it works fine.  So I have been using a uv tools to turn my small little script into a "yt" tool to replace this functionality for fabric.

I did test with yt-dlp directly bypassing fabric.

`yt-dlp --write-subs --write-auto-subs --skip-download https://www.youtube.com/watch?v=vTZ8Y40gK7Y`

**Comment by ksylvan** [comment]
@officiallymarky Please let me know:

1. What version of Fabric are you using?
2. On what operating system
3. Version of yt-dlp

Recently someone was using a much older version of Fabric (I only recently ripped out the no longer working web scraping code)

https://github.com/danielmiessler/Fabric/releases/latest is now 1.4.224

**Comment by officiallymarky** [comment]
> [@officiallymarky](https://github.com/officiallymarky) Please let me know:
> 
> 1. What version of Fabric are you using?
> 2. On what operating system
> 3. Version of yt-dlp
> 
> Recently someone was using a much older version of Fabric (I only recently ripped out the no longer working web scraping code)
> 
> https://github.com/danielmiessler/Fabric/releases/latest is now 1.4.224

yt-dlp --version
2025.02.19

fabric --version
v1.4.210

Arch Linux

Hmm, looks like I do have an older yt-dlp, I did an update and it said it was 6.30 but some reason it is saying it is 2.19.  That might be it, will see what I need to do since --update isn't doing it.

sudo yt-dlp --update
Latest version: stable@2025.06.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.06.30 from yt-dlp/yt-dlp)

# Update

Ok I figured it out.  When I use sudo yt-dlp to update, it says already up to date, because root has access to a yt-dlp than I do as my user.

which yt-dlp
/home/mal/.local/bin/yt-dlp

sudo which yt-dlp
/usr/bin/yt-dlp

# final update

Ok, looks like somewhere it was installed as a uv tool, once I removed it from uv as a tool, it pulled my system one from arch which is in fact latest.  This worked no problem.  So another case of an old version.

**Comment by ksylvan** [comment]
@officiallymarky Thank you.

**Comment by ksylvan** [comment]
Also, you might want to update to version 224. We are getting ready to integrate tools (search tool and image creation) for OpenAI models.

**Comment by officiallymarky** [comment]
> Also, you might want to update to version 224. We are getting ready to integrate tools (search tool and image creation) for OpenAI models.

I am using Arch AUR, and it doesn't look like it is updating that quickly.  I prefer using pacman or aur when possible, but it is too slow, I will install it directly.

**Comment by officiallymarky** [comment]
> Also, you might want to update to version 224. We are getting ready to integrate tools (search tool and image creation) for OpenAI models.

I removed the arch version (which is what the github recommends on arch) since it isn't updating as fast and just did the direct install.  I then created scripts to keep it updated.  I already have a script that updates the patterns and moves over any custom patterns.

I would suggest having it create timers to do auto update and pattern updates in an install or at least have information about doing this in the installation instructions.  

```
[Unit]
Description=Update Fabric binary, patterns, and restore custom patterns
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'curl -L https://github.com/danielmiessler/fabric/releases/latest/download/fabric-linux-amd64 -o %h/.local/bin/fabric && chmod +x %h/.local/bin/fabric && /usr/bin/fabric-ai --updatepatterns && cp -r %h/.config/custompatterns/* %h/.config/fabric/patterns/ 2>/dev/null || true'
Environment=HOME=%h
StandardOutput=null
StandardError=null
```

This is what I am doing.

Is there any future plans to handle custom patterns better?  It's kind of janky how you have to copy your patterns over whenever you update the patterns.  Maybe have the --updatepatterns do this for you.  If you are not as comfortable with scripting, it is probably something most people aren't going to do.

**Comment by ksylvan** [comment]
> Is there any future plans to handle custom patterns better? 

Feel free to create a feature request issue about this and we can brainstorm some ideas for handling it.

**Comment by Jallermax** [comment]
> I've had a similar problem, for me the reason seems to have been a combination between missing `yt-dlp` and using the binary distribution, instead of the Go installation method. After I installed `fabric` using Go, installed `yt-dlp` and setup the `~/yt-dlp.conf` with contents `--cookies-from-browser chrome`, it worked fine. Hope this helps someone.

Thank you @borisuu! This method worked for me.

I had the same error on Windows with the latest yt-dlp version 2025.06.30 and no VPN.

**Comment by ksylvan** [comment]
@officiallymarky in case you missed it I implemented a custom patterns directory. 

Do fabric --setup and follow the prompts.
