### ISSUE TITLE
[Bug]: No Matches Found:

### ISSUE THREAD

**Issue by technotion** [danielmiessler/fabric#1092]
### What happened?

I am attempting to use the `yt` command for applying a pattern to a YouTube video.
I enter the following command with an example URL here:

`yt --transcript https://www.youtube.com/watch?v=zBP2deuPQTg | fabric --model claude-3-5-sonnet-20240620 -sp extract_wisdom`

I receive the following error in the terminal:

`zsh: no matches found: https://www.youtube.com/watch?v=zBP2deuPQTg`

The URL for the video is valid and contains a transcript.
I am working locally on a Mac with the latest version of Fabric.

### Version check

- [X] Yes I was.

**Comment by eugeis** [comment]
It is not about fabric, but your shell, zsh.

"no matches found: ... " means zsh tries to match characters like *,?,....
I need to use quotation marks around the "url", because URL may have ? inside

try this:

fabric -y "https://www.youtube.com/watch?v=zBP2deuPQTg" --model claude-3-5-sonnet-20240620 -sp extract_wisdom
