### ISSUE TITLE
[Bug]: Issue during installation

### ISSUE THREAD

**Issue by bogdanshuliar** [danielmiessler/fabric#161]
### What happened?

I was trying to launch the project (OS Windows), when POETRY installed successfully, but it seems I can't enter OPEN AI key somehow.
Please see the screenshot

### Version check

- [X] Yes I was.

### Relevant screenshots (optional)

![wqd3e23e3e2](https://github.com/danielmiessler/fabric/assets/39959829/049e3c1e-9c85-4ecf-93df-fa66c065a265)

**Comment by waldo323** [comment]
Partial solution/hopefully helpful in getting further/or at least helpful in getting more information which can lease to a solution:

Sounds like poetry is properly installed but isn't getting launched during the setup process.  If you know poetry's location you can try the setup again after add poetry to your path with the command:
export PATH=$PATH:/path/to/folder/where/poetry/is/ 
 Note that this method of adding a folder to your path will only last for this session and when you close that terminal window, that folder will no longer be on the path. (Another way to put this is that you need to use the full path to the program like "/path/to/where/poetry/is/poetry" instead of the much short "poetry" which only works when poetry is on your path

Anyway, once the setup script is successful, you will likely need to add fabric to your patch in the same way.  Once you kno Partial solution/hopefully helpful in getting further/or at least helpful in getting more information which can lease to a solution:

Sounds like poetry is properly installed but isn't getting launched during the setup process.  If you know poetry's location you can try the setup again after add poetry to your path with the command:
export PATH=$PATH:/path/to/folder/where/poetry/is/ 
 Note that this method of adding a folder to your path will only last for this session and when you close that terminal window, that folder will no longer be on the path. (Another way to put this is that you need to use the full path to the program like "/path/to/where/poetry/is/poetry" instead of the much short "poetry" which only works when poetry is on your path

Anyway, once the setup script is successful, you will likely need to add fabric to your patch in the same way.  Once you know that poetry and fabric work when they are added to your path you can add them to your path in a more permanent way.
If you're shell is for instance bash then you are likely missing the .bashrc file (it is run when your shell starts up). this file should be in the root of your home folder when the  setup is run, so the paths can be added to it. It is okay to create an empty file with the proper name for your shell 


While looking for wording for what I think is a git bash shell on windows, I came across the following stack overflow question/answer.
The answer posted "Jun 26, 2019 at 12:33" is the information I already wrote about but with slightly different words and helpful formatting 

- https://stackoverflow.com/questions/45980107/extend-path-variable-in-git-bash-under-windows

there may be a more permanent solution in the works in the fabric setup. this comment is aimed at getting you started 

- not affiliated with the project, James
