### ISSUE TITLE
[Bug]: Drag and Drop files into GUI not working in Linux

### ISSUE THREAD

**Issue by tholonia** [danielmiessler/fabric#418]
### What happened?

Using the GUI interface, when dragging a .txt file into the 'Drop file here' box, no file appears, and if I hit submit (just incase it was there but not listed) I see the message:
```
I'm sorry, but I need some input in order to provide a response. Could you please provide me with the text or statement that you would like me to analyze?
```

### Version check

- [X] Yes I was.

### Relevant log output

```shell
GUI console message

index.js:344 Uncaught ReferenceError: originalPlaceholder is not defined
    at HTMLTextAreaElement.<anonymous> (index.js:344:29)
```
```


### Relevant screenshots (optional)

_No response_

**Comment by epeuu** [comment]
The same issue occurs for me regardless of the file I drag and drop. The file
doesn't appear in the expected location, but when I click 'Submit', numbers like
0,1,1,1,1,1,0,0,0... appear. I'd love to identify the root cause of this problem and
find a solution.

I am running fabric on Windows 11 23H2; fabric-cli works perfectly, but fabric-gui doesn't appear to work as it should.

**Comment by konstantinurban** [comment]
I am having the same issue! I'm using a Mac. And if I hit submit (just incase it was there but not listed) I see no message.

**Comment by fearby** [comment]
Cannot drop files into gui on MacOS also
