### ISSUE TITLE
How do i get/use api keys for the 

### ISSUE THREAD

**Issue by A1codesause** [danielmiessler/fabric#469]
### What is your question?

I have 3 problems
1. I don't know how to get a api key
2. I want to use ollama not open ai if I can help it
3. I'm to inexperienced to know how to ask the right questions to find the right tutorials for 1 and 2

**Comment by armisis** [comment]
1. Getting an API Key
To use an API, you typically need to sign up for a service that provides the API and then generate an API key from their platform. Here's a general guide on how to do it:

Sign Up: Go to the website of the service you want to use (e.g., Ollama).
Create an Account: If you don’t have an account, create one by providing the necessary details.
Access API Section: Once logged in, look for a section related to API access or developer tools. This can usually be found in the account settings or a dedicated developer portal.
Generate API Key: Follow the instructions to generate an API key. This often involves clicking a button like "Generate API Key" and possibly naming the key for your reference.
Copy the Key: Once generated, copy the API key. Be sure to keep it secure and do not share it publicly.
2. Using Ollama Instead of OpenAI
If you prefer to use Ollama, you'll need to follow their specific process for obtaining an API key and accessing their services. Here’s a generalized step-by-step guide:

Visit Ollama’s Website: Navigate to the official Ollama website.
Sign Up or Log In: Create an account or log in if you already have one.
Developer Portal: Find the developer or API section of the website.
Generate API Key: Look for options to generate an API key. Follow the instructions provided by Ollama.
Documentation: Refer to Ollama’s API documentation for specific instructions on how to use their API. This will include details on how to authenticate requests with your API key and examples of how to make API calls.
3. Finding the Right Tutorials
Here are some tips for finding tutorials that will help you with API keys and using specific APIs like Ollama:

Search for Specific Queries: Use search engines with specific queries like “how to get API key for Ollama” or “Ollama API tutorial”.
Developer Documentation: Check the official documentation of the service you’re using. They often have step-by-step guides and examples.
YouTube Tutorials: Look for video tutorials on platforms like YouTube. Search for terms like “Ollama API key tutorial” or “Ollama API integration”.
Developer Forums: Join forums like Stack Overflow, Reddit, or the official forums of the service. You can ask questions or search for similar issues others have faced.
Specific Help for Ollama
If you need specific help with Ollama, I recommend starting with their official documentation and support resources. They likely have guides and support channels to help you get started. If you run into specific issues or errors, you can post detailed questions on forums or seek help from their support team.

**Comment by julliannailluj** [comment]
If you're a Windows user, you can run models locally with Ollama, in a local version of Linux using WSL. Open the Windows terminal and type the lines which don't start with #.

# Install WSL
wsl --install

# In Ubuntu
sudo apt update
sudo apt upgrade

# Install Ollama
curl -fsSL https://ollama.com/install.sh | sh

# Check if it's launched in your browser http://localhost:11434/

# install llama3
ollama pull llama3

Then, you can use Fabric normally, and specify you want to use the local model, for example:

yt --transcript https://www.youtube.com/watch?v=JgsGH5IOCFE | fabric --model llama3:latest -sp extract_wisdom

**Comment by mitchwyle** [comment]
how do i change API keys?  Where are they stored?  TIA
