### ISSUE TITLE
[Feature request]: Update patterns for better local LLM support (suggested fix)

### ISSUE THREAD

**Issue by circbuf255** [danielmiessler/fabric#655]
### What do you need?

After some experimentation, q8 llama3 and mistral **run locally** are performing **much** better after adjusting the prompt order.  I propose restructuring the patterns so that the "# INPUT" text comes before output instructions.  INPUT before OUTPUT INSTRUCTIONS is producing much more coherent responses.

As an example, let's look at **extract_wisdom**:

# **Proposed** prompt order
INPUT
--put your YouTube transcript here--
IDENTITY and PURPOSE
STEPS
OUTPUT INSTRUCTIONS
OUTPUT

# **Current**  prompt order
IDENTITY and PURPOSE
STEPS
OUTPUT INSTRUCTIONS
INPUT

---------------------------------------------------------
Models tested:
llama3:8b-instruct-q8_0
mistral:7b-instruct-v0.2-q8_0

**Comment by timothyjoh** [comment]
Have you tested these with OpenAI and Claude models? How does it perform?

**Comment by ktneely** [comment]
I did some testing with gpt-4o and llama3:instruct.   The difference for GPT due to the re-ordering was fairly minimal.  In one instance, it was slightly better, in the other, slightly worse.  On llama3, I had a few tests that were markedly better, and then a couple where it didn't seem to make a difference.

These were a combination of my own patterns and the default ones, and this was all very "let's take a quick look".  I think it's worth exploring and would be up for some more testing, but I haven't thought of a good approach to this yet.  Maybe the OP has some ideas, or maybe there's a gamut of tests that are used for development?

**Comment by ultibo** [comment]
I've created a prompt to create a cover letter with a certain resume given in the pattern and the job posting given as input. 

The usual template 
```
# IDENTITY and PURPOSE
# STEPS
# OUTPUT INSTRUCTIONS
# CV PROVIDED
# INPUT

```
worked  just fine with GPT4

However when testing on smaller local models ( gemma2:7b and llama3.1:8b) both were giving me an analysis of the job posting, with vague reference from the resume and were not following the instructions what so ever.

I've tested to manually prompt gemma2:7b and llama3.1:8b with the template as follow and it worked just fine, the instructions where followed.
```
I will provide below a CV in the section "CV PROVIDED" and the a job offer in the section "INPUT".
the instructions will be at the end.
# CV PROVIDED
# INPUT
# IDENTITY and PURPOSE
# STEPS
# OUTPUT INSTRUCTIONS
```


This leads me to two questions. 
- how can I see the prompt that is generated by fabric ? From testing it seems it's always at the end, and the "#INPUT" section doen't no to anything.
- would it be interesting to be able to place the "input" anywhere on the template at the variable ?

**Comment by jaredmontoya** [comment]
I am currently working on bringing support for setting default model context length when calling Ollama through fabric.
I suspect that your proposal will not treat the disease but hide it and that the problem that you are trying to solve was already reported and closed *without actually solving it*.

In #743 and #662 users experience that the model forgets it's fabric pattern if the input is too long, and it's exactly what we should expect because the default context window used by Ollama is 2048 tokens (which is not even nearly enough for long youtube transcripts) even if the model supports 132k (because memory consumption grows exponentially and not all Ollama users have enough memory to run the model with it's MAX supported context window) and when an LLM running on Ollama runs out of it's context window set by Ollama it forgets things that came before, including the pattern that tells it what to do with all this.

What I think is that by reordering the prompt like in your proposal the model now forgets it's INPUT first and the pattern LAST so it now follows the pattern better but looses A LOT of information at the start of the youtube video transcript you are trying to use `extract_wisdom` on.

Unfortunately the only cure to this problem is giving the model more memory, and it's not even possible to set using fabric right now(you have to resort to what #662 did), but I already finished my PR #1088 that will allow sending num_ctx(context size) parameter to Ollama and as soon as it is merged and released people will be able to set the context window to the size that they can afford.
