### ISSUE TITLE
[Bug]: PermissionError: [Errno 13] Permission denied: '/Users/USERNAME/.bash_profile' while running fabric --setup on

### ISSUE THREAD

**Issue by universalamateur** [danielmiessler/fabric#759]
### What happened?

I was doing running fabric --setup on, when [Errno 13] Permission denied: '/Users/USERNAME/.bash_profile' happened. I was expecting a success message to happen instead.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
# [Bug]: PermissionError: [Errno 13] Permission denied: '/Users/USERNAME/.bash_profile' while running fabric --setup on


[USERNAME@MBP]─(~/git/fabric)-[$] fabric --setup
Welcome to Fabric. Let's get started.
Please enter your OpenAI API key. If you do not have one or if you have already entered it, press enter.

Please enter your claude API key. If you do not have one, or if you have already entered it, press enter.

Please enter your Google API key. If you do not have one, or if you have already entered it, press enter.

Please enter your YouTube API key. If you do not have one, or if you have already entered it, press enter.

Updating patterns...
Downloaded zip file successfully.
Extracted zip file successfully.
Patterns updated successfully.
Traceback (most recent call last):
  File "/Users/USERNAME/.local/bin/fabric", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/USERNAME/.local/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/fabric.py", line 86, in main
    Setup().run()
  File "/Users/USERNAME/.local/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 803, in run
    self.update_shconfigs()
  File "/Users/USERNAME/.local/pipx/venvs/fabric/lib/python3.12/site-packages/installer/client/cli/utils.py", line 618, in update_shconfigs
    with open(config, 'w') as f:
         ^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/Users/USERNAME/.bash_profile'


```bash
[USERNAME@MBP]─(~/git/fabric)-[$]  ls -la /Users/USERNAME/.bash_profile
-rw-r--r--  1 root  staff  195 May  1  2023 /Users/USERNAME/.bash_profile
```
```


### Relevant screenshots (optional)

_No response_

**Comment by matigumma** [comment]
solution:

`sudo fabric --setup`

**Comment by GuyHoozdis** [comment]
@universalamateur,  it looks like your `.bash_profile` file is owned by `root` instead of `USERNAME`.

```bash
[USERNAME@MBP]─(~/git/fabric)-[$]  ls -la /Users/USERNAME/.bash_profile
-rw-r--r--  1 root  staff  195 May  1  2023 /Users/USERNAME/.bash_profile
```

That is atypical and probably **not** what you want.  To fix the situation, change the owner of the file.  Having the group permissions set to `staff` is typical on a Mac, so you don't need to change that.

Although running `sudo fabric --setup` will get you past the error, it doesn't solve your problem.  Something like that is probably how you got into this situation.  This is how you fix it.

# Changing the owner of `.bash_profile` back to `USERNAME`

Since the file is currently owned by `root` you will need to execute the `chown` (i.e. change owner) command with `sudo`. (You need to use `sudo` because the file is currently owned by not you, so you need elevated privileges to make a change like this).

```bash
$ sudo chown USERNAME /Users/USERNAME/.bash_profile
```

Afterwards, if you look at the file again, you should see something like this:
```bash
[USERNAME@MBP]─(~/git/fabric)-[$]  ls -la /Users/USERNAME/.bash_profile
-rw-r--r--  1 USERNAME  staff  195 May  1  2023 /Users/USERNAME/.bash_profile
```

Now run `fabric --setup` and you should not get that same error message anymore.

## In case things in your home directory really got messed up

In general, everything in `/Users/USERNAME` should be owned by `USERNAME`.  If you look and see that other files have the same issue, then you can apply the `chown` command recursively.  Use `:<group>` to apply a group at the same time.

This will change every file and directory in `USERNAME`'s home directory `/Users/USERNAME/` to have owner `USERNAME` and group `staff`.
```bash
$ sudo chown -R USERNAME:staff /Users/USERNAME/
```

# If you intentionally have .bash_profile owned by root

_Note: I do not recommend this and unless you know what you are doing you should be using the solution above._

In the off chance that you actually _want_ `root` to own `/Users/USERNAME/.bash_profile`, then I'm guessing your error is coming from the fact that `USERNAME` can't write to `.bash_profile`.  I say that because the file is set so that anyone can read it, but right now only `root` can write to it.

Your user likely already is a member of the `staff` group.  You can verify with this command:

```bash
$ whoami
USERNAME

$ id -Gn USERNAME
staff [... and more...]
```

Now, let members of the group `staff` write to `.bash_profile` with the `chmod` (change file modes) command:

```bash
$ sudo chmod g+w /Users/USERNAME/.bash_profile
```

Again, you'll have to run that command using `sudo`.  You can verify that you now have write access by opening the file, making an edit like leaving a comment, and then saving the file.  If you can save it, then you have write access.

After that, the `fabric --setup`
