### ISSUE TITLE
[Question]: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by jdjb78** [danielmiessler/fabric#766]
### What is your question?

After reading the documentation, I am still not clear how to get ChatGPT working. I tried increasing my quota, but am still getting quota limits when doing an extract_wisdom from a yt video. Switching to Gemini works, but it doesn't give as good of a response as ChatGPT. I'm using model gpt-4o-2024-05-13

**Comment by GuyHoozdis** [comment]
@jdjb78 , are you seeing an error message like this?

```python
{'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.',
  'type': 'insufficient_quota',
  'param': None,
  'code': 'insufficient_quota'}}
```

If so, I'm getting the same error.  I'm using the free tier.  Since you are using the `gpt-4o-2024-05-13` model, I take it that you have a paid account.

@jdjb78 , would you try using the `gpt-4-turbo-preview` model and see what happens?  

My first attempt at running `extract_wisdom` over the transcript output by `yt` gave an error message that indicated that was the model it wanted to use.  I want to rule out the possibility that there is some feature or functionality supported by that model that the models you and I are using do not have.

**Comment by jordanw** [comment]
The other issue could be the policy change where you have to pre-pay. I just had that error message and it was because I ran out of the balance that I had pre-loaded.
