### ISSUE TITLE
[Bug]: Reopen #827 stream error: stream ID 3; CANCEL; received from peer

### ISSUE THREAD

**Issue by caunus** [danielmiessler/fabric#876]
### What happened?

Hi,
I’m not sure if this is the correct way to report this bug again, but since the original bug report #827 was already closed, I wasn`t sure how to reopen a closed report.

I tried to install Fabric on a Raspberry Pi 4 with 4GB RAM for some remote shell scripting. Long story short, I encountered the same error message as in report #827: “stream error: stream ID 3; CANCEL; received from peer.” This happened consistently. I tried changing the OpenAI models and also switched to an Ollama server on my network, trying different models as well. The same error occurred.

However, here’s what worked: I ran the setup again with OpenAI until the error appeared, then copied the pattern folder from my MacBook to the Raspberry Pi. After that, everything worked fine.
Thanks, Caunus

### Version check

- [X] Yes I was.

### Relevant log output

```shell
stream error: stream ID 3; CANCEL; received from peer happened
```

### Relevant screenshots (optional)

See bug #827 , just the same

**Comment by caunus** [comment]
Is there any news on that? Tried today to install the new version, but there is still the same error.

**Comment by marcelritzschke** [comment]
I just ran into the same issue and I have the feeling it is simply a timeout due to slow network speed, since it always happens when downloading a larger file (i.e. `images/fabric-logo-gif.gif` > 40MB).

Also in [HTTP2 spec](https://datatracker.ietf.org/doc/html/rfc7540#section-8.2.2 ) it says:
> if the server takes too long to begin sending the promised response, the client can send a RST_STREAM frame, using either the CANCEL or REFUSED_STREAM code and referencing the pushed stream's identifier

Are you able to try a different network?

**Comment by caunus** [comment]
Thanks. I switch from WiFi to Ethernet and now it works. The Raspi stands nearby the router and upgrades big kernel files very well over WiFi so I never tested it before.  Thanks again.

**Comment by marcelritzschke** [comment]
If there are others that run into the same issue and can not simply switch to a faster network, it seems the root cause is the git clone via HTTP during setup process. 

You can try to clone the repo via SSH instead, for that make sure you have generated an SSH key and added to your github account ([generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux) and [adding-a-new-ssh-key-to-your-github-account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account))

Then in your active shell start the ssh-agent and add your key:
``` bash
# linux, add ssh key to local agent
eval `ssh-agent`
ssh-add
```

Finally call `fabric --setup` and when you get asked "Enter the default Git repository URL for the patterns ..." use:
``` bash
git@github.com:danielmiessler/fabric.git
```

**Comment by aguiarrlucas** [comment]
Any other solutions? I tried all these things and it still didn't work

**Comment by salmansarwar5102** [comment]
Getting the same error when downloading patterns:

`[Patterns Loader]

Enter the default Git repository URL for the patterns (leave empty for 'https://github.com/danielmiessler/fabric.git' or type 'reset' to remove the value):


Enter the default folder in the Git repository where patterns are stored (leave empty for 'patterns' or type 'reset' to remove the value):

Downloading patterns and Populating /home/sam/.config/fabric/patterns..

stream error: stream ID 3; CANCEL; received from peer`
