### ISSUE TITLE
[Bug]: yt tool inside fabric not working

### ISSUE THREAD

**Issue by Uddhav07** [danielmiessler/fabric#926]
### What happened?

![image](https://github.com/user-attachments/assets/c4a30394-5bb2-4141-bafb-c253b92dee77)

### Version check

- [X] Yes I was.

**Comment by SME6** [comment]
I don't know if it is related or what. But I haven't been able to install the yt tool.

When putting "go install github.com/danielmiessler/yt@latest" in terminal, I received the message that "**go cannot find GOROOT directory: /usr/local/go.**" 

Any idea if what you posted has anything to do with issue im struggling?

**Comment by carvierdotdev** [comment]
Hi I had a similar error I don't know exactly about Windows and the Environment Variables but for me I have Ubuntu and I try with this export. It's not the same as the README file I don't know exactly about go but this is the only export who solved the problem to find GOROOT and GOPATH:

```zsh
export PATH=$PATH:$(go env GOPATH)/bin
```

The problem I have is different that's why I enter to this issue but maybe this help

**Comment by carvierdotdev** [comment]
> I don't know if it is related or what. But I haven't been able to install the yt tool.
> 
> When putting "go install github.com/danielmiessler/yt@latest" in terminal, I received the message that "**go cannot find GOROOT directory: /usr/local/go.**"

Hi I had a similar error I don't know exactly about Windows and the Environment Variables but for me I have Ubuntu and I try with this export. It's not the same as the README file I don't know exactly about go right now but this is the only export who solved the problem to find GOROOT and GOPATH:

```zsh
export PATH=$PATH:$(go env GOPATH)/bin
```

The problem I have is different that's why I enter to this issue but maybe this help. Also I use that env to install Fabric and yt tool as the README said but I tried yt tool outside fabric. I don't have the option to run it inside fabric I don't know why and I have the latest version of Fabric installed I run `fabric -h` but I don't see that option

**Comment by eugeis** [comment]
Please use fabric -y "url" ...
