### ISSUE TITLE
[Question]: Go: Cannot find GOROOT directory 

### ISSUE THREAD

**Issue by Christoph-Beckmann** [danielmiessler/fabric#971]
### What is your question?

Hey,

In front of the upgrade from Python to Go, I installed "Go" via the Homebrew Package Manager. I had some troubles at first, but in the end, it worked out.

## Problem Statement

Now, I want to upgrade my Fabric version via `go install github.com/danielmiessler/fabric@latest`, and I ran into the following error: `go: cannot find GOROOT directory: /opt/homebrew/bin/go`.

## Setup Information

- I used the Homebrew Package Manager to install Go.
- I have an Apple M1 chip.
- I added the following environment variables to '.zshenv': 

```
export GOROOT="/opt/homebrew/bin/go"
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$PATH"
```

## What did I check?
- I checked the `homebrew/bin/` location and found the alias for `go`.
- `$GOPATH` also exists. 
- `$PATH` is integrated.

**Comment by iancd-hofy** [comment]
Using the prefix link for Goroot worked for me.
`export GOROOT="$(brew --prefix golang)/libexec"`

**Comment by beecave-homelab** [comment]
Had the same error. What i've learned so far is If you installed Go with Homebrew, you normally do not need to manually set `GOROOT`, because Go automatically detects its installation path. 

Homebrew installs Go in `/opt/homebrew/opt/go`, and the go tool should handle `GOROOT` correctly without explicit setting. So, removing `GOROOT` from your `~/.zshrc` could be an option to simplify your configuration.

For instance, try removing `GOROOT` from your `.zshrc` and just keep `GOPATH`:
```bash
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$HOME/.local/bin:$PATH
```

Then reload your environment:
```bash
source ~/.zshrc
```

**Comment by eugeis** [comment]
Please use updated README.md desc.

export GOROOT=$(brew --prefix go)/libexec
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$PATH
