### ISSUE TITLE
[Question]: How to make yt command work?

### ISSUE THREAD

**Issue by pycanis** [danielmiessler/fabric#998]
### What is your question?

I installed fabric by downloading the binary from the release page. It seems it didn't bring "yt" along. What can I do to get it?

`command not found: yt`

**Comment by youthcity** [comment]
I got the same error message:
```
zsh: command not found: yt
```

**Comment by Juliusshipton** [comment]
So I got it installed and ran fabric -h

here I found that -- transcript is an application option of fabric ... so no need for yt?  

I then ran ...

`fabric --transcript https://www.youtube.com/watch?v=ajneRM-ET1Q'

Which gave me this ... 

`zsh: no matches found: https://www.youtube.com/watch?v=ajneRM-ET1Q'

Does this mean it is looking for the youtube video and didn't find it?  I tried to wrap the url in '' and ran this ...

`fabric --transcript 'https://www.youtube.com/watch?v=ajneRM-ET1Q''

Which works ... but spits out the description of a random youtube video every time ... not the description of the video url I put in.

**Comment by pycanis** [comment]
> `fabric --transcript 'https://www.youtube.com/watch?v=ajneRM-ET1Q''

My LLM just replies:

`I can't access or watch YouTube videos. However, I can try to help you discuss the video if you'd like to share more about it! What's the video about?`

**Comment by Juliusshipton** [comment]
Do you have your youtube api setup in you .config/fabric/.env?

Also what LLM are you using?  I only have gemini configed.

**Comment by Juliusshipton** [comment]
That exact command for me is doing a random video every time.

`fabric --transcript 'https://www.youtube.com/watch?v=ajneRM-ET1Q''

Output ...

**Title:** Why Are We So Bad at Predicting the Future?

**Description:**

In this TED-Ed video, Dr. Gerd Gigerenzer, a renowned psychologist, explores the complexities of predicting the future and why humans are often not very good at it. He discusses various cognitive biases and limitations that can hinder our ability to make accurate predictions.

**Key Points:**

* **The Illusion of Knowledge:** We often overestimate our knowledge and ability to predict the future, leading to overconfidence.
* **Confirmation Bias:** We tend to seek out information that confirms our existing beliefs, which can lead us astray.
* **Hindsight Bias:** Once an event has occurred, we tend to believe we could have predicted it, even though we couldn't have.
* **The Curse of Expertise:** Experts in a field may become too focused on details and miss broader patterns.
* **The Power of Simple Rules:** Sometimes, simple rules or heuristics can be more effective for predicting than complex models.

**Conclusion:**

Dr. Gigerenzer emphasizes that predicting the future is inherently difficult due to the uncertainties and complexities involved. However, he encourages us to be mindful of our cognitive biases and to use a variety of tools and strategies to improve our predictions.
(base) juliusshipton@Juliuss-MacBook-Pro fabric % fabric --transcript 'https://www.youtube.com/watch?v=ajneRM-ET1Q'
**Title:** How To Make A Perfect Poached Egg | Chef Jean-Pierre

**Description:**

In this video, Chef Jean-Pierre demonstrates his technique for poaching a perfect egg. He uses a simple method that involves creating a whirlpool in a pot of simmering water and then gently sliding the egg into the center. The result is a poached egg with a tender, velvety interior and a delicate, slightly runny yolk.

**Steps:**

1. Fill a pot with about 2 inches of water and bring it to a simmer.
2. Add 1 tablespoon of white vinegar to the water. This will help the egg white to set more quickly.
3. Use a spoon to create a whirlpool in the center of the water.
4. Carefully crack an egg into a small bowl.
5. Gently slide the egg into the center of the whirlpool.
6. Cook the egg for 2-3 minutes, or until the white is set and the yolk is still slightly runny.
7. Remove the egg from the water with a slotted spoon and drain it on paper towels.
8. Serve the poached egg immediately.

**Tips:**

* Use fresh eggs for best results.
* Don't overcook the egg, or the yolk will become hard and dry.
* If you don't have a slotted spoon, you can use a regular spoon to remove the egg from the water. Just be careful not to break the egg.
* You can add other ingredients to the water to flavor the poached egg, such as salt, pepper, or herbs.

**Comment by Juliusshipton** [comment]
`fabric --transcript 'https://www.youtube.com/watch?v=ajneRM-ET1Q''

This command is giving me a description like this for a random video every time ...

**Title:** How To Make A Perfect Poached Egg | Chef Jean-Pierre

**Description:**

In this video, Chef Jean-Pierre demonstrates his technique for poaching a perfect egg. He uses a simple method that involves creating a whirlpool in a pot of simmering water and then gently sliding the egg into the center. The result is a poached egg with a tender, velvety interior and a delicate, slightly runny yolk.

**Steps:**

1. Fill a pot with about 2 inches of water and bring it to a simmer.
2. Add 1 tablespoon of white vinegar to the water. This will help the egg white to set more quickly.
3. Use a spoon to create a whirlpool in the center of the water.
4. Carefully crack an egg into a small bowl.
5. Gently slide the egg into the center of the whirlpool.
6. Cook the egg for 2-3 minutes, or until the white is set and the yolk is still slightly runny.
7. Remove the egg from the water with a slotted spoon and drain it on paper towels.
8. Serve the poached egg immediately.

**Tips:**

* Use fresh eggs for best results.
* Don't overcook the egg, or the yolk will become hard and dry.
* If you don't have a slotted spoon, you can use a regular spoon to remove the egg from the water. Just be careful not to break the egg.
* You can add other ingredients to the water to flavor the poached egg, such as salt, pepper, or herbs.

**Comment by Juliusshipton** [comment]
Which is also weird because shouldn't this just be the video transcript that is then piped into the extract_wisdom pattern ?

**Comment by eugeis** [comment]
`  -y, --youtube=                   YouTube video "URL" to grab transcript, comments from it and send to chat
      --transcript                      Grab transcript from YouTube video and send to chat (it used per default).
      --comments                    Grab comments from YouTube video and send to chat`

I updated the example description, you can use:

fabric -y "https://www.youtube.com/watch?v=ajneRM-ET1Q" ...

--transcript is a boolean flag, to express that transcript shall be retrieved (is active per default if no YouTube flags are active)
--comments is a boolean flag, to express that comments shall be retrieved

**Comment by Juliusshipton** [comment]
Dude no way ... 

fabric -y "https://www.youtube.com/watch?v=ajneRM-ET1Q"

This worked perfectly!  

Appreciate you!

**Comment by Juliusshipton** [comment]
googleapi: Error 400: Developer instruction is not enabled for models/gemini-pro

Now getting this when trying to pipe transcript into extract wisdom with the command below.

fabric -y "https://youtube.com/watch?v=uXs-zPc63kM" | fabric -p extract_wisdom

If I just run 'fabric -p extract_wisdom' I get another summary of a random thing

**Comment by Juliusshipton** [comment]
Ok even weirder ... I changed the model I'm using (no longer gemini pro)

This command works perfectly fine ...

'fabric -y "https://youtube.com/watch?v=ajneRM-ET1Q" | fabric --stream -p extract_wisdom'

The correct video is identified and it starts to extract wisdom and starts to stream the output .. however the output is stopped and I get this message!?!

blocked: candidate: FinishReasonSafety

I asked Gemini what this is about and it said this ...

> You're receiving the "blocked: candidate: FinishReasonSafety" error when accessing me (or a similar language model) through an API because the system has identified a potential safety risk in your request. This is a common safety measure implemented to prevent harmful or inappropriate content from being generated.
> Here's why this might be happening:
> Your prompt contains potentially unsafe or harmful content: The language model detects elements in your request that could be interpreted as:
> Hate speech: This includes

Is this something builtin to Gemini preventing the put based on my request?   Seems like everything fabric side is Ok.

**Comment by JMcrafter26** [comment]
I just used yt-dlp (with pip) like this:
`yt-dlp --skip-download --write-auto-sub --sub-lang "en" https://www.youtube.com/watch?v= ...`
